import type {
  Cafeteria,
  Category,
  MasterItem,
  MenuItem,
  Order,
  User,
} from "../types";

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "student@keat.ac.in",
    phone: "+91 98765 43210",
    role: "student",
    is_active: true,
  },
  {
    id: 2,
    name: "Priya Patel",
    email: "staff@keat.ac.in",
    phone: "+91 98765 43211",
    role: "staff",
    is_active: true,
  },
  {
    id: 3,
    name: "Ramesh Verma",
    email: "kitchen@keat.ac.in",
    phone: "+91 98765 43212",
    role: "cafe_staff",
    is_active: true,
    cafeterias: [
      {
        assignment_id: 1,
        cafeteria_id: 1,
        cafeteria_name: "Central Food Court",
        role: "manager",
      },
      {
        assignment_id: 2,
        cafeteria_id: 2,
        cafeteria_name: "North Campus Bites",
        role: "staff",
      },
    ],
  },
  {
    id: 4,
    name: "Administrator",
    email: "admin@keat.ac.in",
    phone: "+91 98765 43299",
    role: "admin",
    is_active: true,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: "Breakfast & Tiffins", description: "Hot, freshly prepared breakfast items" },
  { id: 2, name: "Meals & Thalis", description: "Satisfying full meals and combo bowls" },
  { id: 3, name: "Snacks & Quick Bites", description: "Crispy snacks and evening refreshers" },
  { id: 4, name: "Beverages & Shakes", description: "Chilled juices, cold coffees and hot chai" },
  { id: 5, name: "Desserts", description: "Sweet delights and ice creams" },
];

export const MOCK_CAFETERIAS: Cafeteria[] = [
  {
    id: 1,
    name: "Central Food Court",
    location: "Student Activity Center (SAC) Ground Floor",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    is_open: true,
    is_active: true,
    manager_id: 3,
    payment_instructions: "UPI: centralfc@upi / GooglePay / PhonePe. Verify UTR number at the pickup counter.",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "North Campus Bites",
    location: "Engineering Block 3, North Wing",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    is_open: true,
    is_active: true,
    payment_instructions: "Scan QR placed on kiosk or Pay via UPI: northbites@upi",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Brew & Bake Cafe",
    location: "Central Library Garden Courtyard",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    is_open: true,
    is_active: true,
    payment_instructions: "Cash or UPI to brewbake@upi accepted.",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Night Owl Canteen",
    location: "Hostel Quadrangle Canteen 2",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=80",
    is_open: false,
    is_active: true,
    payment_instructions: "Open 8:00 PM - 2:00 AM. UPI only.",
    created_at: new Date().toISOString(),
  },
];

export const MOCK_MASTER_ITEMS: MasterItem[] = [
  {
    id: 1,
    name: "Masala Dosa",
    description: "Crispy fermented crepe stuffed with spiced potato mash, served with sambar and coconut chutney.",
    category_id: 1,
    category_name: "Breakfast & Tiffins",
    price: 60.0,
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 2,
    name: "Idli Vada Combo",
    description: "Two steamed rice cakes and one crispy medu vada with hot sambar and chutney.",
    category_id: 1,
    category_name: "Breakfast & Tiffins",
    price: 50.0,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 3,
    name: "Special Veg Thali",
    description: "Paneer butter masala, dal tadka, jeera rice, 2 butter rotis, salad, papad, and gulab jamun.",
    category_id: 2,
    category_name: "Meals & Thalis",
    price: 120.0,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 4,
    name: "Paneer Tikka Roll",
    description: "Char-grilled cottage cheese cubes wrapped in flaky paratha with mint mayo and onions.",
    category_id: 3,
    category_name: "Snacks & Quick Bites",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 5,
    name: "Classic Samosa (2 pcs)",
    description: "Golden fried pastry with savory potato & pea filling with sweet imli & green chutneys.",
    category_id: 3,
    category_name: "Snacks & Quick Bites",
    price: 30.0,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 6,
    name: "Cold Coffee with Ice Cream",
    description: "Rich blended espresso milk topped with a scoop of vanilla ice cream and chocolate drizzle.",
    category_id: 4,
    category_name: "Beverages & Shakes",
    price: 70.0,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 7,
    name: "Masala Chai",
    description: "Traditional milk tea brewed with crushed ginger, cardamom, and aromatic spices.",
    category_id: 4,
    category_name: "Beverages & Shakes",
    price: 20.0,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
  {
    id: 8,
    name: "Warm Chocolate Brownie",
    description: "Gooey chocolate walnut brownie with hot fudge sauce.",
    category_id: 5,
    category_name: "Desserts",
    price: 75.0,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    is_active: true,
  },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    cafeteria_id: 1,
    item_id: 1,
    name: "Masala Dosa",
    description: "Crispy fermented crepe stuffed with spiced potato mash, served with sambar and coconut chutney.",
    category_id: 1,
    category_name: "Breakfast & Tiffins",
    price: 60.0,
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    stock: 25,
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 1,
    item_id: 2,
    name: "Idli Vada Combo",
    description: "Two steamed rice cakes and one crispy medu vada with hot sambar and chutney.",
    category_id: 1,
    category_name: "Breakfast & Tiffins",
    price: 50.0,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    stock: 18,
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 1,
    item_id: 3,
    name: "Special Veg Thali",
    description: "Paneer butter masala, dal tadka, jeera rice, 2 butter rotis, salad, papad, and gulab jamun.",
    category_id: 2,
    category_name: "Meals & Thalis",
    price: 120.0,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    stock: 12,
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 1,
    item_id: 4,
    name: "Paneer Tikka Roll",
    description: "Char-grilled cottage cheese cubes wrapped in flaky paratha with mint mayo and onions.",
    category_id: 3,
    category_name: "Snacks & Quick Bites",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80",
    stock: 3, // low stock!
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 1,
    item_id: 6,
    name: "Cold Coffee with Ice Cream",
    description: "Rich blended espresso milk topped with a scoop of vanilla ice cream and chocolate drizzle.",
    category_id: 4,
    category_name: "Beverages & Shakes",
    price: 70.0,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80",
    stock: 30,
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 1,
    item_id: 7,
    name: "Masala Chai",
    description: "Traditional milk tea brewed with crushed ginger, cardamom, and aromatic spices.",
    category_id: 4,
    category_name: "Beverages & Shakes",
    price: 20.0,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    stock: 50,
    is_available: true,
    reorder_level: 10,
  },
  // Cafeteria 2 menu items
  {
    cafeteria_id: 2,
    item_id: 4,
    name: "Paneer Tikka Roll",
    description: "Char-grilled cottage cheese cubes wrapped in flaky paratha with mint mayo and onions.",
    category_id: 3,
    category_name: "Snacks & Quick Bites",
    price: 85.0,
    image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80",
    stock: 15,
    is_available: true,
    reorder_level: 5,
  },
  {
    cafeteria_id: 2,
    item_id: 5,
    name: "Classic Samosa (2 pcs)",
    description: "Golden fried pastry with savory potato & pea filling with sweet imli & green chutneys.",
    category_id: 3,
    category_name: "Snacks & Quick Bites",
    price: 30.0,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    stock: 40,
    is_available: true,
    reorder_level: 10,
  },
  {
    cafeteria_id: 2,
    item_id: 7,
    name: "Masala Chai",
    description: "Traditional milk tea brewed with crushed ginger, cardamom, and aromatic spices.",
    category_id: 4,
    category_name: "Beverages & Shakes",
    price: 20.0,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    stock: 60,
    is_available: true,
    reorder_level: 10,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 101,
    user_id: 1,
    cafeteria_id: 1,
    cafeteria_name: "Central Food Court",
    total_amount: 145.0,
    status: "preparing",
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    pickup_time: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    customer_name: "Aarav Sharma",
    customer_email: "student@keat.ac.in",
    items: [
      { item_id: 1, name: "Masala Dosa", quantity: 1, unit_price: 60.0, line_total: 60.0 },
      { item_id: 4, name: "Paneer Tikka Roll", quantity: 1, unit_price: 85.0, line_total: 85.0 },
    ],
    payment: {
      id: 201,
      order_id: 101,
      payment_method: "upi",
      amount: 145.0,
      status: "success",
      transaction_id: "UPI9823487192",
      verified_by: 3,
      verified_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      cafeteria_name: "Central Food Court",
    },
    queue: {
      queue_item_id: 1,
      position: 2,
      orders_ahead: 1,
    },
  },
  {
    id: 102,
    user_id: 1,
    cafeteria_id: 1,
    cafeteria_name: "Central Food Court",
    total_amount: 70.0,
    status: "not_paid",
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    pickup_time: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    customer_name: "Aarav Sharma",
    customer_email: "student@keat.ac.in",
    items: [
      { item_id: 6, name: "Cold Coffee with Ice Cream", quantity: 1, unit_price: 70.0, line_total: 70.0 },
    ],
    payment: {
      id: 202,
      order_id: 102,
      payment_method: "upi",
      amount: 70.0,
      status: "pending",
      transaction_id: null,
      cafeteria_name: "Central Food Court",
      payment_instructions: "UPI: centralfc@upi / GooglePay / PhonePe. Verify UTR number at the pickup counter.",
    },
    queue: null,
  },
  {
    id: 100,
    user_id: 1,
    cafeteria_id: 1,
    cafeteria_name: "Central Food Court",
    total_amount: 120.0,
    status: "collected",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
    pickup_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    customer_name: "Aarav Sharma",
    customer_email: "student@keat.ac.in",
    items: [
      { item_id: 3, name: "Special Veg Thali", quantity: 1, unit_price: 120.0, line_total: 120.0 },
    ],
    payment: {
      id: 200,
      order_id: 100,
      payment_method: "upi",
      amount: 120.0,
      status: "success",
      transaction_id: "UPI8721639102",
      verified_by: 3,
      verified_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      cafeteria_name: "Central Food Court",
    },
    queue: null,
  },
];
